### ISSUE TITLE
Make attrs>=0.17 an installation requirement

### ISSUE THREAD

**Issue by jluttine** [warner/magic-wormhole#248]
*EDIT: There's a lot stuff here, but in the end, upgrading attrs to 17.2.0 fixed the issue. Could you make attrs>=17 as an installation requirement?*

Hi, any idea why I get a large number of test failures and errors:
```
FAILED (skips=21, failures=6, errors=74, successes=248)
```

Full log here: https://gist.github.com/jluttine/84832bacf93b385bf37721c320788203

Errors like:
- `exceptions.AttributeError: 'Boss' object has no attribute '_RC'`
- `exceptions.AttributeError: 'CodeInputter' object has no attribute '_committed_nameplate'`
- and some other similar `AttributeError`s

Any ideas what could be wrong here?

**Comment by jluttine** [comment]
This is perhaps related to some change between 0.9.2 and 0.10.2 because 0.9.2 succeeds but 0.10.2 fails.

**Comment by jluttine** [comment]
I'm trying to fix the packaging of magic-wormhole for NixOS. The packaging worked for 0.9.2 but not for 0.10.2 anymore. I tested whether the addition of txtorcon could have affected but I get the same errors when I run the test suite without txtorcon. So I'm a bit out of ideas.

**Comment by jluttine** [comment]
I did `git bisect` on one of the failing tests and found this as the first failing commit:

```
73f3d8610748a40c1dd9fc792d6aba4055d46bc0 is the first bad commit
commit 73f3d8610748a40c1dd9fc792d6aba4055d46bc0
Author: Brian Warner <warner@lothar.com>
Date:   Thu Dec 15 00:04:17 2016 -0800

    state machine should be complete, I think

:100644 100644 e8ff35b06134d34cd949dba93622fb7bf4e8e628 24101acee7faf5046130ba1d2fc0c0ffd53dfeb7 M      setup.py
:040000 040000 a7a24eb39b9dec672cf8008b2d6d3b544ffb3571 eb819a977cfdbdf945d49364ffd9f46879770d6e M      src
```

**Comment by jluttine** [comment]
Nope, that wasn't quite right. Need to do it again.

**Comment by jluttine** [comment]
Well, this bisecting seems a bit difficult:

- 0.10.0 broken
- ...
- https://github.com/warner/magic-wormhole/commit/d0d2992d4491791fd263517488842b2d32e8aff6 first broken with similar errors as I mentioned
- https://github.com/warner/magic-wormhole/commi/b981b4260dd5204a1b5c96dab36dbe98d9393e4d the previous commit suddenly doesn't find the relevant tests, just some other errors. This error stays for some time when moving back in the commit history.
- When moving closer to 0.9.2 there seems to be also some other different test failures, so I don't know whether I should mark those as good or bad in bisecting.

So, it's a bit difficult to use the tests for bisecting if they're broken most of the time and for different reasons, so you can't really say whether the different error is just hiding the other error, or the other way around, or whether they are totally different.

Any hints would be useful...

**Comment by jluttine** [comment]
I did a git bisect so that any failure is considered bad. This might not find the commit that has caused the actual bug in the original post. Here's the git bisect procedure if anyone's interested: https://gist.github.com/jluttine/8370fa53254097357620f3617b67391b One can clearly see how it finds different errors for the same test.

**Comment by jluttine** [comment]
As I'm using NixOS, my main hypotheses for the errors are:

- Could I be missing some relevant system package (e.g., command line tool) or Python package?

- Are there assumptions in wormhole on how some libraries or executables are located in the filesystem? Could violation of those cause the errors?

**Comment by jluttine** [comment]
```
$ pip freeze
asn1crypto==0.22.0
attrs==16.2.0
autobahn==17.8.1
Automat==0.6.0
cffi==1.10.0
characteristic==14.3.0
click==6.7
constantly==15.1.0
cryptography==1.8.1
funcsigs==1.0.2
hkdf==0.0.3
humanize==0.5.1
hyperlink==17.3.0
idna==2.5
incremental==17.5.0
ipaddress==1.0.18
-e git+https://github.com/warner/magic-wormhole@572f6e3c16a550a0427fd7e9026547a6712aacdc#egg=magic_wormhole
mock==2.0.0
packaging==16.8
pbr==3.1.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
PyNaCl==0.3.0
pyOpenSSL==17.0.0
pyparsing==2.2.0
service-identity==16.0.0
six==1.10.0
spake2==0.7
tqdm==4.15.0
Twisted==17.5.0
txaio==2.8.1
txtorcon==0.19.3
zope.event==4.0.3
zope.interface==4.4.2
```

**Comment by jluttine** [comment]
Upgrading attrs to 0.17.2 fixed the issue. Could you make >=0.17 as an installation requirement?

**Comment by warner** [comment]
Ah, good catch, it was obviously wrong for us to be using attrs without depending upon it. And it looks like 16.3.0 is the first version that provided the `__attrs_post_init__()` feature that we use, so I'll add a `attrs >= 16.3.0` to the `setup.py`. Thanks!
